downgrade to 1.10.3

diff --git a/scripts/base b/scripts/base
--- a/scripts/base
+++ b/scripts/base
@@ -42,7 +42,7 @@ then
   do
     if [[ -f "$rvmrc" ]]
     then
-      if GREP_OPTIONS="" \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
+      if \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
       then
         printf "%b" "
 Error:
@@ -56,6 +56,18 @@ Error:
     fi
   done
 fi
+
+export rvm_tar
+export rvm_uname
+rvm_uname=$(uname)
+case "$rvm_uname" in
+    OpenBSD)
+        rvm_tar=gtar
+        ;;
+    *)
+        rvm_tar=tar
+        ;;
+esac
 
 export rvm_path
 if [[ -z "${rvm_path:-}" ]]
@@ -83,7 +95,6 @@ case " ${rvm_base_except:-} " in
     ;;
   (*)
     source "$rvm_scripts_path/selector"
-    source "$rvm_scripts_path/selector_gemsets"
     ;;
 esac
 
@@ -95,3 +106,10 @@ for entry in ${scripts[@]} ; do
   source "$rvm_scripts_path/functions/$entry"
 done
 unset scripts entry rvm_base_except
+
+if [[ ! -t 0 ]] && builtin command -v __rvm_cleanup_tmp >/dev/null 2>&1
+then
+  # Cleanup RVM temporary files on exit if we are loaded from a script.
+  # Only cleanup if the function to do so is defined :)
+  trap "set +e; __rvm_cleanup_tmp '$$'" 0 1 2 3 15
+fi
diff --git a/scripts/cli b/scripts/cli
--- a/scripts/cli
+++ b/scripts/cli
@@ -1,27 +1,38 @@
 #!/usr/bin/env bash
 
 __rvm_usage() {
-  __rvm_pager_or_cat_v "${rvm_path:-$HOME/.rvm}/README"
+  eval "${PAGER:-cat -v} '${rvm_path:-$HOME/.rvm}/README'"
 }
 
 __rvm_run_script()
 {
-  "$rvm_scripts_path/${1:-"$rvm_action"}" "${rvm_ruby_args[@]}"
+  typeset rvm_script_name
+  rvm_script_name="${1:-"$rvm_action"}"
+
+  eval "$rvm_scripts_path/$rvm_script_name $rvm_ruby_args"
+
+  return $?
 }
 
 __rvm_parse_args()
 {
   typeset _string
-  export rvm_ruby_string
+  # TODO:
+  #       Make this more robust '__rvm_history' so that it stores *unique* rvm commands.
+  #       Otherwise this file gets big rather fast.
+  #echo "$@" >> $HOME/.rvm_history
 
-  rvm_action="${rvm_action:-""}"
-  rvm_parse_break=0
-
-  if [[ " $* " =~ " --trace " ]]
+  if echo "$@" | \grep 'trace'  >/dev/null 2>&1
   then
     echo "$@"
     __rvm_version
   fi
+
+  rvm_action="${rvm_action:-""}"
+
+  export rvm_ruby_string
+
+  rvm_parse_break=0
 
   while [[ -n "$next_token" ]]
   do
@@ -72,17 +83,17 @@ __rvm_parse_args()
 
             if [[ -z "$next_token" ]]
             then
-              rvm_ruby_args=("help")
+              rvm_ruby_args="help"
 
             elif [[ "clear" == "$next_token" ]]
             then
               __rvm_gemset_clear
-              rvm_ruby_args=("clear")
+              rvm_ruby_args="clear"
 
             elif [[ "use" == "$next_token" ]]
             then
               rvm_use_flag=1
-              rvm_ruby_args=("$next_token" "$@")
+              rvm_ruby_args="$next_token $@"
               rvm_gemset_name="$next_token"
               if (( $# > 0 ))
               then
@@ -116,7 +127,7 @@ __rvm_parse_args()
             elif [[ "delete" == "$next_token" ]]
             then
               rvm_delete_flag=1
-              rvm_ruby_args=("$next_token" "$@")
+              rvm_ruby_args="$next_token $@"
 
               if [[ $# -gt 0 ]] ; then next_token="$1" ; shift ; else next_token="" ; fi
 
@@ -139,15 +150,14 @@ __rvm_parse_args()
 
             else
               if [[ "${rvm_ruby_string:-""}" != "${rvm_gemset_name:-""}" ]] ; then __rvm_ruby_string ;  fi
-              rvm_ruby_args=("$next_token" "$@")
+              rvm_ruby_args="$next_token $@"
             fi
 
-: rvm_ruby_args:${rvm_ruby_args[*]}:
             rvm_parse_break=1
             ;;
 
           gemdir|gempath|gemhome)
-            rvm_ruby_args=("$rvm_token")
+            rvm_ruby_args="$rvm_token"
             rvm_action="gemset"
             rvm_gemdir_flag=1
 
@@ -171,7 +181,7 @@ __rvm_parse_args()
               shift
               rvm_only_path_flag=1
             fi
-            rvm_ruby_args=("$next_token" "$@")
+            rvm_ruby_args="$next_token $*"
             rvm_parse_break=1
             ;;
 
@@ -184,31 +194,24 @@ __rvm_parse_args()
 
 
           do|exec|gem|rake|ruby)
-            if [[ "$rvm_token" == "ruby" ]] && [[ "$rvm_action" == "install" || "$rvm_action" == "use" ]]
-            then
-              rvm_ruby_string=ruby
-              rvm_ruby_strings=ruby
-              continue
-            fi
             if [[ -z "$next_token" ]]
             then
-              rvm_action="error"
-              rvm_error_message="'rvm $rvm_token' must be followed by arguments."
-              break
+                rvm_action="error"
+                rvm_error_message="'rvm $rvm_action' must be followed by arguments."
             fi
             rvm_action="do"
             rvm_parse_break=1
             case "$rvm_token" in
               do|exec)
                 # deprecation for exec removed after discsussion with Wayne
-                rvm_ruby_args=("$next_token" "$@")
+                rvm_ruby_args="$next_token $(__rvm_quote_args "$@")"
                 ;;
               *)
                 # TODO: deprecation issued on 2011.10.11, for RVM 1.9.0
                 rvm_warn "Please note that \`rvm $rvm_token ...\` is only an alias to \`rvm do $rvm_token ...\`,\n"\
                   "it might work different as in earlier versions of RVM and will be shortly removed!\n"\
                   "Also note that you do not have to prefix every command with \`rvm\`, they should just work by itself."
-                rvm_ruby_args=("$rvm_token" "$next_token" "$@")
+                rvm_ruby_args="$rvm_token $next_token $(__rvm_quote_args "$@")"
                 ;;
             esac
             ;;
@@ -221,7 +224,7 @@ __rvm_parse_args()
             rvm_action=$rvm_token
             while [[ -n "${next_token:-}" ]] && [[ -x "${next_token:-}" || -d "${next_token:-}" ]]
             do
-              rvm_ruby_args=("$next_token" "${rvm_ruby_args[@]}")
+              rvm_ruby_args="$next_token ${rvm_ruby_args:-}"
               if (( $# > 0 ))
               then
                 next_token="$1"
@@ -247,31 +250,32 @@ __rvm_parse_args()
             if [[ "ls" == "$rvm_action" ]]; then rvm_action="list" ; fi
 
             rvm_action="$rvm_token"
-            rvm_ruby_args=("$next_token" "$@" )
+            rvm_ruby_args=("$next_token" "$@" ) # params parsing for zsh
+            rvm_ruby_args="${rvm_ruby_args[*]}"
             rvm_parse_break=1
             ;;
 
           docs|alias|rubygems|cleanup|tools|disk-usage|snapshot|repair|migrate|upgrade)
             rvm_action="$rvm_token"
-            rvm_ruby_args=("$next_token" "$@")
+            rvm_ruby_args="$next_token $(__rvm_quote_args "$@")"
             rvm_parse_break=1
             ;;
 
           user)
             rvm_action="tools"
-            rvm_ruby_args=("$rvm_token" "$next_token" "$@")
+            rvm_ruby_args="$rvm_token $next_token $(__rvm_quote_args "$@")"
             rvm_parse_break=1
             ;;
 
           load-rvmrc)
             rvm_action="rvmrc"
-            rvm_ruby_args=("load" "$next_token" "$@")
+            rvm_ruby_args="'load' $next_token $(__rvm_quote_args "$@")"
             rvm_parse_break=1
             ;;
 
           rvmrc)
             rvm_action="rvmrc"
-            rvm_ruby_args=("$next_token" "$@")
+            rvm_ruby_args="$next_token $(__rvm_quote_args "$@")"
             rvm_parse_break=1
             ;;
 
@@ -282,7 +286,7 @@ __rvm_parse_args()
 
           specs|tests)
             rvm_action="rake"
-            rvm_ruby_args=("${rvm_token/%ss/s}")
+            rvm_ruby_args="${rvm_token/%ss/s}"
             ;;
 
           export)
@@ -299,19 +303,13 @@ __rvm_parse_args()
 
           group)
             rvm_action="group"
-            rvm_ruby_args=("$next_token" "$@")
-            rvm_parse_break=1
-            ;;
-
-          alt*)
-            rvm_action="help"
-            rvm_ruby_args=("alt.md")
+            rvm_ruby_args="$next_token $@"
             rvm_parse_break=1
             ;;
 
           help|usage)
             rvm_action="help"
-            rvm_ruby_args=("$next_token" "$@")
+            rvm_ruby_args="$next_token $@"
             rvm_parse_break=1
             ;;
 
@@ -333,7 +331,7 @@ __rvm_parse_args()
             else
               next_token=""
             fi
-            rvm_ruby_args=("$next_token" "$@") # list of binaries, or none
+            rvm_ruby_args="$next_token $@" # list of binaries, or none
             rvm_parse_break=1
             ;;
 
@@ -425,7 +423,7 @@ __rvm_parse_args()
                     ;;
 
                   *.rb) # we have a specified ruby script
-                    rvm_ruby_args=("$rvm_token")
+                    rvm_ruby_args="$rvm_token"
                     rvm_ruby_file="$rvm_token"
 
                     if [[ -z "${rvm_action:-""}" || "$rvm_action" == "use" ]]; then
@@ -439,7 +437,7 @@ __rvm_parse_args()
                       rvm_ruby_strings="$rvm_token"
                       rvm_action="${rvm_action:-use}"
 
-                    elif  __rvm_project_dir_check "$rvm_token"
+                    elif [[ -d $rvm_token && -f $rvm_token/.rvmrc && -s $rvm_token/.rvmrc ]]
                     then
                       __rvm_rvmrc_tools try_to_read_ruby $rvm_token
 
@@ -466,15 +464,13 @@ __rvm_parse_args()
         case "$rvm_token" in
           -S)
             rvm_action="ruby"
-            rvm_ruby_args=("$rvm_token" "$next_token" "$@")
+            rvm_ruby_args="$rvm_token $next_token $(__rvm_quote_args "$@")"
             rvm_parse_break=1
             ;;
 
           -e)
             rvm_action="ruby"
-            IFS="\n"
-            rvm_ruby_args=("$rvm_token" "'$next_token $@'")
-            IFS=" "
+            IFS="\n" ; rvm_ruby_args="$rvm_token '$next_token $@'" ; IFS=" "
             rvm_parse_break=1
             ;;
 
@@ -494,12 +490,6 @@ __rvm_parse_args()
 
           --branch)
             rvm_ruby_repo_branch="$next_token"
-            next_token="${1:-""}"
-            shift
-            ;;
-
-          --sha)
-            rvm_ruby_sha="$next_token"
             next_token="${1:-""}"
             shift
             ;;
@@ -690,13 +680,7 @@ __rvm_parse_args()
             export "rvm_${rvm_token}_flag"=1
             ;;
 
-          --rvmrc|--versions-conf|--ruby-version)
-            rvm_token=${rvm_token#--}
-            rvm_token=${rvm_token//-/_}
-            export rvm_rvmrc_flag="${rvm_token}"
-            ;;
-
-          --self|--gem|--rubygems|--reconfigure|--default|--force|--export|--summary|--latest|--yaml|--json|--archive|--shebang|--env|--path|--tail|--delete|--verbose|--import|--sticky|--create|--gems|--docs|--skip-autoreconf|--18|--19|--force-autoconf|--auto|--autoinstall-bundler|--ignore-gemsets)
+          --self|--gem|--rubygems|--reconfigure|--default|--force|--export|--summary|--latest|--yaml|--json|--archive|--shebang|--env|--path|--tail|--delete|--verbose|--import|--rvmrc|--sticky|--create|--gems|--docs|--skip-autoreconf|--18|--19|--force-autoconf|--auto)
             rvm_token=${rvm_token#--}
             rvm_token=${rvm_token//-/_}
             export "rvm_${rvm_token}_flag"=1
@@ -776,7 +760,7 @@ __rvm_parse_args()
           --)
             if [[ "${rvm_action}" == *install ]]
             then rvm_configure_flags="${rvm_configure_flags:-""} $next_token  $*"
-            else rvm_ruby_args=("$next_token" "$@")
+            else rvm_ruby_args="$next_token $*"
             fi
             rvm_parse_break=1
             ;;
@@ -789,9 +773,9 @@ __rvm_parse_args()
         ;;
 
       *)
-        if __rvm_project_dir_check "$rvm_token"
+        if [[ -d $rvm_token && -f $rvm_token/.rvmrc && -s $rvm_token/.rvmrc ]]
         then
-          __rvm_rvmrc_tools try_to_read_ruby "$rvm_token"
+          __rvm_rvmrc_tools try_to_read_ruby $rvm_token
 
         else # People who are smoking crack.
           rvm_action="error"
@@ -817,59 +801,30 @@ __rvm_parse_args()
 rvm()
 {
   typeset result current_result
-  export -a rvm_ruby_args >/dev/null 2>/dev/null
 
-  if (( ${rvm_ignore_rvmrc:=0} == 0 ))
+  if [[ -n "${BASH_VERSION:-}" ]]
   then
-    : rvm_stored_umask:${rvm_stored_umask:=$(umask)}
-    for rvmrc in /etc/rvmrc "$HOME/.rvmrc"
-    do
-      if [[ -f "$rvmrc" ]]
-      then
-        if GREP_OPTIONS="" \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
-        then
-          printf "%b" "
-Error:
-        $rvmrc is for rvm settings only.
-        rvm CLI may NOT be called from within $rvmrc.
-        Skipping the loading of $rvmrc"
-          return 1
-        else
-          source "$rvmrc"
-        fi
-      fi
-    done
+    trap '__rvm_teardown_final' 0 1 2 3 15
   fi
 
-  disk_version="$(cat "$rvm_path/VERSION") ($(cat "$rvm_path/RELEASE" 2>/dev/null))"
-  if [[ -s "$rvm_path/VERSION" &&
-    "${rvm_version:-}" != "${disk_version:-}" &&
-    "reload" != "${1:-}" ]]
-  then
-    if [[ ${rvm_auto_reload_flag:-0} -gt 0 ]]
-    then
-      __rvm_project_rvmrc_lock=0
-      rvm_reload_flag=1
-      source "${rvm_scripts_path:-${rvm_path}/scripts}/rvm"
-    else
-      printf "%b" "
-A RVM version ${disk_version} is installed yet ${rvm_version} is loaded.
-Please do one of the following:
-  * 'rvm reload'
-  * open a new shell
-  * 'echo rvm_auto_reload_flag=1 >> ~/.rvmrc' # for auto reload with msg.
-  * 'echo rvm_auto_reload_flag=2 >> ~/.rvmrc' # for silent auto reload.
-
-"
-      return 1
-    fi
-  fi
+  next_token="$1"
+  [[ $# -eq 0 ]] || shift
 
   __rvm_initialize
   __rvm_setup
 
-  next_token="$1"
-  [[ $# -eq 0 ]] || shift
+  # Check that this is the current version, after rvm_path has been determined.
+  disk_version=$(cat "$rvm_path/VERSION" 2>/dev/null)
+  disk_version="${disk_version/%.}"
+
+  if [[ -n "${rvm_version:-""}" &&
+    "${rvm_version:-""}" != "${disk_version:-""}" &&
+    "reload" != "${next_token:-""}" ]]
+  then
+    printf "%b" "\nA RVM version ${disk_version} is installed yet ${rvm_version} is loaded.\n Please do one of the following:\n  * 'rvm reload'\n  * open a new shell\n\n"
+    return 1
+  fi
+
   __rvm_parse_args "$@"
   result=$?
 
@@ -878,8 +833,16 @@ Please do one of the following:
   [[ $result -gt 0 ]] ||
   case "$rvm_action" in
     use)
-      if rvm_is_a_shell_function
-      then __rvm_use
+      if [[ "${rvm_is_not_a_shell_function:-0}" == "1" ]]
+      then
+        if rvm_pretty_print stderr
+        then
+          printf "%b" "\n${rvm_error_clr:-}RVM is not a function, selecting rubies with '${rvm_notify_clr:-}rvm use ...${rvm_error_clr:-}' will not work.${rvm_reset_clr:-}\n" >&2
+        else
+          printf "%b" "\nRVM is not a function, selecting rubies with 'rvm use ...' will not work.\n" >&2
+        fi
+      else
+        __rvm_use
       fi
       ;;
     srcdir)
@@ -892,7 +855,7 @@ Please do one of the following:
       __rvm_version
       ;;
     ls|list)
-      "$rvm_scripts_path/list" "${rvm_ruby_args[@]}"
+      "$rvm_scripts_path"/list $rvm_ruby_args
       ;;
 
     # TODO: Make debug run in the current environment, issues with not exported vars.
@@ -927,22 +890,26 @@ Please do one of the following:
       ;;
 
     get)
-      next_token="${1:-}"
-      (( $# > 0 )) && shift
-      [[ "$next_token" == "${rvm_action}" ]] && shift
+      if (( $# > 0 ))
+      then
+        next_token="$1"
+        shift
+      else
+        next_token=""
+      fi
 
+      if [[ "$next_token" == "${rvm_action}" ]]
+      then
+        shift
+      fi
       tmpdir=${TMPDIR:-/tmp}
       \cp -f "$rvm_scripts_path/get" $tmpdir/$$
-      if "$SHELL" "$tmpdir/$$" "${rvm_ruby_args[@]}"
-      then
-        rvm_reload_flag=1
-      else
-        rvm_error "Could not update RVM, get some help at #rvm IRC channel at freenode servers."
-      fi
+      "$SHELL" "$tmpdir/$$" $rvm_ruby_args
       \rm -f $tmpdir/$$
+      rvm_reload_flag=1
       ;;
 
-    help|rtfm|env|current|list|monitor|notes|package|extract|pkg|requirements)
+    help|rtfm|env|current|list|gemdir|gemhome|gempath|monitor|notes|package|extract|pkg|requirements)
 
       if (( $# > 0 ))
       then
@@ -957,19 +924,19 @@ Please do one of the following:
         shift
       fi
 
-      "$rvm_scripts_path/${rvm_action}" "${rvm_ruby_args[@]}"
+      "$rvm_scripts_path/${rvm_action}" ${rvm_ruby_args:-}
       ;;
 
     info)
-      rvm_is_not_a_shell_function="${rvm_is_not_a_shell_function}" "$rvm_scripts_path/${rvm_action}" "${rvm_ruby_args[@]}"
+      rvm_is_not_a_shell_function="${rvm_is_not_a_shell_function}" "$rvm_scripts_path/${rvm_action}" ${rvm_ruby_args:-}
       ;;
 
     cleanup|tools|snapshot|disk-usage|repair|alias|docs|rubygems|migrate|upgrade)
-      __rvm_run_script "$rvm_action" "${rvm_ruby_args[@]}"
+      __rvm_run_script "$rvm_action" "$rvm_ruby_args"
       ;;
 
     wrapper)
-      "$rvm_scripts_path/wrapper" "$rvm_ruby_string" "$rvm_wrapper_name" "${rvm_ruby_args[@]}"
+      "$rvm_scripts_path/wrapper" "$rvm_ruby_string" "$rvm_wrapper_name" $rvm_ruby_args
       unset rvm_wrapper_name
       ;;
 
@@ -978,8 +945,10 @@ Please do one of the following:
       unset rvm_ruby_string
       export rvm_ruby_strings
 
-      "$rvm_scripts_path/set" "$rvm_action" "${rvm_ruby_args[@]}"
-      result=$?
+      if [[ "${rvm_is_not_a_shell_function:-0}" == "1" ]]
+      then eval exec "$rvm_scripts_path/set" "$rvm_action" $rvm_ruby_args
+      else eval "'$rvm_scripts_path/set' '$rvm_action' $rvm_ruby_args" ; result=$?
+      fi
 
       # Restore the state pre-sets.
       [[ -n "$old_rvm_ruby_string" ]] && rvm_ruby_string=$old_rvm_ruby_string
@@ -988,18 +957,20 @@ Please do one of the following:
       ;;
 
     rvmrc)
-      __rvm_rvmrc_tools "${rvm_ruby_args[@]}"
+      # Leave the eval for quoted arguemnt passing.
+      eval "__rvm_rvmrc_tools $rvm_ruby_args"
     ;;
 
     gemset)
 
-      if [[ ${rvm_use_flag:-0} -eq 1 ]]
-      then
-        __rvm_gemset_use
+      if [[ ${rvm_use_flag:-0} -eq 1 ]] ; then
+        __rvm_gemset_select &&
+          rvm_log "Using ${GEM_HOME%@*} with gemset ${rvm_gemset_name:-default}" &&
+          __rvm_gemset_use
       else
         export rvm_ruby_strings
 
-        "$rvm_scripts_path/gemsets" "${rvm_ruby_args[@]}" ; result=$?
+        "$rvm_scripts_path/gemsets" $rvm_ruby_args ; result=$?
 
         rvm_ruby_strings=""
 
@@ -1026,18 +997,7 @@ Please do one of the following:
       rvm_action="rake" ; __rvm_do
       ;;
 
-    remove)
-      export rvm_path
-      if [[ -n "${rvm_ruby_strings}" ]]
-      then
-        "$rvm_scripts_path"/manage "$rvm_action" "${rvm_ruby_strings//*-- }"
-      else
-        "$rvm_scripts_path"/manage "$rvm_action"
-      fi
-      rvm_ruby_string=default
-      __rvm_use
-      ;;
-    fetch|uninstall|reinstall)
+    fetch|uninstall|remove|reinstall)
       export rvm_path
       if [[ -n "${rvm_ruby_strings}" ]]
       then
@@ -1052,12 +1012,7 @@ Please do one of the following:
       then
         typeset save_ruby
         selected_ruby="$( __rvm_select && echo $rvm_env_string )"
-        if [[ -z "${selected_ruby}" ]]
-        then
-          rvm_error "Could not detect ruby version/name for installation, please be more specific."
-          false #report error
-
-        elif (( ${rvm_force_flag:-0} == 0 )) && "$rvm_scripts_path"/list strings | GREP_OPTIONS="" \grep "^${selected_ruby}$" > /dev/null
+        if (( ${rvm_force_flag:-0} == 0 )) && "$rvm_scripts_path"/list strings | grep "^${selected_ruby}$" > /dev/null
         then
           rvm_log "Already installed ${selected_ruby}.
 To reinstall use:
@@ -1074,7 +1029,7 @@ To reinstall use:
       ;;
 
     mount|automount)
-      "${rvm_scripts_path}/external" "$rvm_action" "${rvm_ruby_args[@]}"
+      "${rvm_scripts_path}/external" "$rvm_action" $rvm_ruby_args
       ;;
 
     export)
@@ -1113,26 +1068,14 @@ To reinstall use:
   # Use the result of first found error
   (( result > 0 )) || result=${current_result}
 
-  [[ $result -gt 0 ]] ||
-  case "$rvm_action" in
-    reinstall|try_install|install)
-      if [[ $(ls -1 $rvm_rubies_path/*/bin/ruby | wc -l) -eq 1 ]] &&
-        [[ ! -f "${rvm_environments_path}/default" ]]
-      then
-        if rvm_is_a_shell_function
-        then rvm_default_flag=1 __rvm_use
-        fi
-      fi
-    ;;
-  esac
-  current_result=$?
-  # Use the result of first found error
-  (( result > 0 )) || result=${current_result}
-
   if [[ ${rvm_reload_flag:-0} -eq 1 ]]
   then
-    __rvm_project_rvmrc_lock=0
+    rvm_loaded_flag=0
     source "$rvm_scripts_path/rvm"
+    unset rvm_reload_flag
+
+    # Note: Not using builtin on purpose. Done so we can trigger a reload the rvmrc.
+    __rvm_project_rvmrc
   fi
 
   typeset __local_rvm_trace_flag
diff --git a/scripts/info b/scripts/info
--- a/scripts/info
+++ b/scripts/info
@@ -154,7 +154,7 @@ $(__rvm_version)
 
   for file_name in "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.zshenv" ; do
     if [[ -s "$file_name" ]] ; then
-      rvm_info="$rvm_info\n$file_name:\n$(GREP_OPTIONS="" \grep 'rvm' "$file_name" 2>/dev/null || true)"
+      rvm_info="$rvm_info\n$file_name:\n$(\grep 'rvm' "$file_name" 2>/dev/null || true)"
     fi
   done
 
@@ -217,7 +217,15 @@ if [[ -z "${sections// /}" ]] ; then
   sections="$all_sections"
 fi
 
-rvm_is_a_shell_function || true
+if [[ "${rvm_is_not_a_shell_function:-0}" == "1" ]]
+then
+  if rvm_pretty_print stderr
+  then
+    printf "%b" "\n${rvm_notify_clr:-}RVM is not a function, selecting rubies with '${rvm_error_clr:-}rvm use ...${rvm_notify_clr:-}' will not work.${rvm_reset_clr:-}\n" >&2
+  else
+    printf "%b" "\nRVM is not a function, selecting rubies with 'rvm use ...' will not work.\n" >&2
+  fi
+fi
 
 if [[ -z "$ruby_strings" ]] ; then
 
